[project]
name = "f1-el"
version = "0.1.0"
description = "Extract & Load code from F1 API to PostgreSQL database."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.1.0",
]
